### ISSUE TITLE
UniformRandomBackOffPolicy loses maxBackOffPeriod when withSleeper is used

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-retry#234]
Currently UniformRandomBackOffPolicy loses maxBackOffPeriod when withSleeper is used, and the following test fails:

```
        @Test
	public void testSetSleeper() {
		UniformRandomBackOffPolicy backOffPolicy = new UniformRandomBackOffPolicy();
		int minBackOff = 1000;
		int maxBackOff = 10000;
		backOffPolicy.setMinBackOffPeriod(minBackOff);
		backOffPolicy.setMaxBackOffPeriod(maxBackOff);
		UniformRandomBackOffPolicy withSleeper = backOffPolicy.withSleeper(new DummySleeper());

		assertEquals(minBackOff, withSleeper.getMinBackOffPeriod());
		assertEquals(maxBackOff, withSleeper.getMaxBackOffPeriod());
	}

```

**Comment by tomazfernandes** [comment]
@garyrussell, I came across this bug when testing this policy for the RetryTopic feature in Spring Kafka. I'll open a PR with this test and the fix, hope it's ok. I've fixed this manually in the RetryTopic logic; when a Spring Retry release comes out with this fix we can remove that.

**Comment by artembilan** [comment]
> ... I came across this bug when testing this policy ....
> ... I've fixed this manually in the RetryTopic ...

Can we instead of local fix for this policy in that project just use a different one for testing?

**Comment by tomazfernandes** [comment]
Hi @artembilan, I'm not sure I understand what you're proposing - this is the piece of code I was referring to: https://github.com/spring-projects/spring-kafka/pull/1734/files#diff-e1592509316884f5d7610eb59d8d05311f3b0d03ab62bfa44bc779ee2bb5bef4R82

It's up to the users to use this policy or not - this code is just to make sure it works as expected.

Maybe I'm missing something?

**Comment by tomazfernandes** [comment]
For clarification, the RetryTopic functionality in Spring Kafka works with any implementation of Spring Retry's SleepingBackOffPolicy interface, plus NoBackOffPolicy - the user can even provide a custom one.

**Comment by artembilan** [comment]
Yes, it's up to end-user to chose the policy. And that is great that you have chosen this one to catch this problem.
Since we have figured out the fix and it is approved, I don't see a reason to keep that `// UniformRandomBackOffPolicy loses the max value when a sleeper is set.` comment, plus a workaround. 

My suggestion is to move away from workaround and extra comment in Spring Kafka to some other retry policy. 
The point is that you make too much code changes and some of them are fully not related to the original issue. 
It is very hard to review your fixes since they are changing drastically.

Your contribution is still very appreciated, but to have more productive collaboration (we can't accept your changes without review), it is better to look to your fixes from our perspective and how it is going to be hard for us to review it. So, better to make smaller PRs with more concentrated fix or just refactoring, even if work is not done, we always can have more PRs. Right now we are stuck over there because too much breaking changes in a very big PR. Sorry for frustrating you, but there is a teamwork to bear with and you should be ready for any feedback 😉 

Merging your PR here and see you later in the other one elsewhere!

**Comment by tomazfernandes** [comment]
Hi @artembilan, I'm really sorry that PR is giving you such a headache.

I see now that instead of splitting it in two halfs for the same issue / PR I should have created just the one with the first half, 
added the corresponding documentation and tests, and left the actual refactoring in a different separate issue / PR.
And sure separate any changes that are not related to the issue in different PRs.

As for the frustation part - that's no frustration at all! This is pretty much my first time contributing to OSS, and that has already shown me a totally different view on the work I do (or can do) and even my career as a whole, so I'm only ever so grateful for all the support I've been having.

I do appreciate very much you calling out what I can do to make more productive contributions - I'll do my best to make good on that.

Let me know if there's anything else I can do to help.

Thanks!

**Comment by artembilan** [comment]
All good, @tomazfernandes ! 

Let's just stop polluting issue for this Spring Retry project! 😉 

We always can continue discussion some other place where you can reach us.

As for the help: you can just go over Spring Kafka issues: https://github.com/spring-projects/spring-kafka/issues, since it looks like you are familiar with the project already 😄 

Thank you again!
