### ISSUE TITLE
Configuration of List of RetryListener does not work as of 1.3.1

### ISSUE THREAD

**Issue by dougtedd** [spring-projects/spring-retry#237]
In 1.3.0 it was possible to define a global List of RetryListener using the following configuration:
```
@Bean
public List<RetryListener> retryListener() {
    return List.of(retryListener1, retryListener2, ...);
}
```
As of 1.3.1 this no-longer works. Instead only a single instance can be configured as follows:
```
@Bean
public RetryListener singleRetryListener() {
    return retryListener1;
}
```

The change in behaviour is due to the recent update in class org.springframework.retry.annotation.RetryConfiguration. The following method returns null when called from line 92 to get the List of RetryListener beans: `<T> List<T> findBeans(Class<? extends T> type)`

The attached test passes with 1.3.0 but fails with 1.3.1.
[retry.zip](https://github.com/spring-projects/spring-retry/files/6167485/retry.zip)

Not clear if this was an intentional change or if it is a bug in 1.3.1.

**Comment by garyrussell** [comment]
I believe that the reason it "worked" previously was a coincidental happenstance because the listeners were previously `@Autowired` as a list with the generic type; it relied on Spring's capability of assembling individual listener beans into a `List<RetryListener>`. 

It was not designed to inject a `List<RetryListener>` bean. 

Generally, beans of `java.util.<any container>` are discouraged because it can cause early instantiation of all such collections.

The proper way to reinstate this functionality would be to introduce a `RetryListeners` wrapper around a collection of listeners.

We can't use the bean factory to `getBeansOfType(List.class)` for the reasons I stated.

**Comment by jonblack** [comment]
The `findBeans` method of `RetryConfiguration` will return `null` now if there are multiple `RetryListener` beans configured:

https://github.com/spring-projects/spring-retry/blob/62d7bfefb6ebd444219afec8f8bc5d833936a32e/src/main/java/org/springframework/retry/annotation/RetryConfiguration.java#L103-L113

This change looks like a mistake because the method returns a list but that list can only ever contain a single bean, making the intention really unclear.

**Comment by artembilan** [comment]
It looks like you are right. That `if (listable.getBeanNamesForType(type).length == 1) {` is a copy/paste artefact from the the next `findBean()` method. Since we are in the intent to get all the beans of the provided type, we must not have such a filter in the logic and just return everything what was requested.

**Comment by garyrussell** [comment]
It should probably use the `getBeansOfType(type, false, false)` variant also.
