### ISSUE TITLE
@Retryable is not working for generic methods

### ISSUE THREAD

**Issue by KaisNeffati** [spring-projects/spring-retry#278]
Hello there,

We have a common generic method enabling us to perform HTTP requests. We have a problem annotating this method by @Retryable

This is an example :

```
    @Retryable(maxAttempts = 10, backoff = @Backoff(delay = 100))
    public <T> T processCall(Call<T> call, String method) {
        throw new RuntimeException("Hello");
    }
```

**Comment by snicoll** [comment]
What version are you using and what do you mean by "not working"?

**Comment by KaisNeffati** [comment]
Hello @snicoll , Thank you very much for your prompt response 

Okay, so "not working" means, not doing the retry - it executes just one time

We are on the following versions:
JAVA version : 17
Spring boot : 2.5.8
Spring retry: 1.3.1

**Comment by snicoll** [comment]
Please try with `1.3.2`. If that still doesn't work, we'd need a small sample we can run ourselves.

**Comment by garyrussell** [comment]
Did you add `@EnableRetry` to one of your `@Configuration` classes? That triggers the framework to look for `@Retryable` methods.

Other common mistakes is to call a `@Retryable` method from within the same class; that won't work, because it bypasses the advice; retryable methods must be called from another bean.

**Comment by KaisNeffati** [comment]
Thank you @garyrussell I think that was the problem; Please Close this issue @snicoll 

Best luck
