### ISSUE TITLE
@Retryable exclude option does not work as expected

### ISSUE THREAD

**Issue by ldhartzman** [spring-projects/spring-retry#47]
I have a method that throws a user-defined exception for a particular circumstance but should not be the reason for a retry and was added to the `exclude` option value.

Another user-defined exception is added to the `include` option of @Retryable and there is an accompanying @Recover.

If the exception that is supposed to be excluded from retry is thrown, an ExhaustedRetryException is thrown with a message complaining about a missing @Recover method (for the excluded exception). The `count` for the retry is 1 when this occurs.

The `policyMap` has the excluded exception in it with a value of `false`, but is not being properly handled.

The @Retryable annotation also has a `backoff` option defined along with `maxAttempts` set to 5.

**Comment by dsyer** [comment]
I think I understand the problem. That's actually the expected behaviour - you don't see any retry for the exception that you excluded, and there is no recovery path in a stateful retry (you didn't say that it was but I guess it must be) - but it's unexpected because you specifically excluded that exception. You might expect the original exception to be thrown, so you can do that with `throwLastExceptionOnExhausted` in the `RetryTemplate` (but there's no setter for it in `@Retryable`). Not sure how to fix the unexpected behaviour.

**Comment by artembilan** [comment]
For this kind of task we have since `2.0`:
```
	/**
	 * Exception types that are not recoverable; these exceptions are thrown to the caller
	 * without calling any recoverer (immediately if also in {@link #noRetryFor()}).
	 * Defaults to empty.
	 * @return exception types not to retry
	 * @since 2.0
	 */
	Class<? extends Throwable>[] notRecoverable() default {};
```

So, treating it as `Fixed` via: https://github.com/spring-projects/spring-retry/issues/264
