### ISSUE TITLE
Rework Exception-wrapping

### ISSUE THREAD

**Issue by jbspeakr** [spring-projects/spring-retry#82]
Currently, `@CircuitBreaker` always wraps failures into into an `ExhaustedRetryException`. This hides the true nature of the failure and makes it furthermore impossible to figure out whether the circuit breaker is actually open or not.

Having e.g. a `@Recover`-method just to unwrap and rethrow exceptions seems not a proper way to go... it also doesn't solve the circuit breaker status issue. 

The only currently available alternative is to implement a custom circuit breaker `RetryTemplate` which feels odd.

Please fix.

**Comment by dsyer** [comment]
It's not really a `@CircuitBreaker` feature is it (the `RetryTemplate` always wraps the last failed exception)?
It has been like that since the beginning, and therefore there might be reasons and also people relying on the behaviour, so "please fix" is kind of irresponsible. If you have a concrete suggestion about how to evolve the code please feel free to comment or send patches.
